Footwear:
  - SHOES
  - BOOT
  - SANDAL
  - TECHNICAL_SPORT_SHOE
  - SLIPPER
  - SLIP_ON_SHOE
  - ATHLETIC_SHOE
  - RUNNING_SHOE

Furniture:
  - SOFA
  - CHAIR
  - TABLE
  - FURNITURE
  - HOME_FURNITURE_AND_DECOR
  - HOME_BED_AND_BATH
  - BED
  - MATTRESS
  - DESK
  - BOOKCASE
  - CABINET
  - SHELF
  - STOOL
  - BENCH

Electronics_Accessories:
  - CELLULAR_PHONE_CASE
  - HEADPHONES
  - SPEAKERS
  - COMPUTER
  - COMPUTER_COMPONENT
  - COMPUTER_ADD_ON
  - ELECTRONICS
  - COMPUTER_ACCESSORY
  - KEYBOARD
  - MOUSE
  - MONITOR
  - WEBCAM
  - USB_FLASH_DRIVE
  - MEMORY_CARD
  - POWER_ADAPTER
  - CHARGER
  - PHONE_ACCESSORY

Fashion_Travel:
  - HANDBAG
  - BACKPACK
  - SUITCASE
  - LUGGAGE
  - TOTE_BAG
  - BAG
  - STORAGE_BAG
  - TRAVEL_ACCESSORY
  - WALLET
  - PURSE
  - DUFFEL_BAG
  - BRIEFCASE

Home_Kitchen:
  - HOME
  - KITCHEN
  - DRINKING_CUP
  - PANTRY
  - SAUTE_FRY_PAN
  - DISHWARE_PLATE
  - BAKEWARE
  - KITCHEN_KNIFE
  - KITCHEN_TOOLS
  - COOKWARE
  - CUTTING_BOARD
  - FOOD_STORAGE_CONTAINER
  - BOWL
  - MUG
  - GLASS
  - DINNERWARE
  - COFFEE_MAKER
  - TOASTER
  - BLENDER

Hardware_HomeImprovement:
  - HARDWARE
  - HARDWARE_HANDLE
  - BUILDING_MATERIAL
  - TOOLS
  - TOOL
  - FASTENER
  - SCREW
  - NAIL
  - DRILL
  - HAMMER
  - WRENCH
  - PLIERS
  - PAINT_BRUSH
  - LOCK
  - DOOR_HANDLE